django/insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static      # static method 가져오기.
from django.conf import settings                # settings.py 의 file을 가져오기.
from accounts import views as accounts_views    # 이름 혼동을 피하기 위해 accounts_views  변수명을 변경.



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),    # 대괄호 안에 내용물 뒤에 ,쉼표를 꼭 붙이는 습관을 들이는 게 좋다.
    path('posts/', include('posts.urls')),
    path('<str:username>/', accounts_views.people, name = 'people'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 주소를 업로드.

django/insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name='list'),
    path('explore/', views.explore, name='explore'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'), 
    # <>부분은 variable routing 이라고 각기 다른 값을 넣을 수 있다.
    path('<int:post_id>/comments/create/', views.comment_create, name ='comment_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete', views.comment_delete, name = 'comment_delete'),
    path('<int:post_id>/like/', views.like, name = 'like'),
    
]

django/insta/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

def post_image_path(instance, filename):
    return f'posts/images/{filename}'  # f 스트링 사용. filename에 확장자가 포함되어 있음.
    # 폴더이름에 들어가면 안되는 기호가 있기때문에 content 를 쓰는건 바람직하지 않다.
    # {instance.pk} 도 데이터베이스에 저장이 안되면 id가 생성되지 않기 때문에 오류가 날 수 있다.


# Create your models here.
class Post(models.Model):
    # 특정한 하나의 유저가 게시할 수 있는 게시글은 여러 개이다. (1:N 관계형성)
    # 위의 경우 N이 누구의 것인지 표시하는 게 효율적이다.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # 다 삭제에 노출되는 CASCADE 라는 옵션.
    # 외래키를 담는다. 다른 모델을 들고와도 반영할 수 있는 장점이 있다.(공식문서 권유기준)
    content = models.TextField()
    # image = models.ImageField(blank=True)   # image라는 이름의 column을 추가!
    # (blank=True) 없으면 이미지가 없을 때 오류가 난다.
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'like_posts')
    
# Post:Image = 1:N
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)    # 이게 뭔 의미지??? 19.04.15
    file = ProcessedImageField(
                    upload_to = post_image_path, # 저장 위치
                    processors = [ResizeToFill(600,600)],   # 처리할 작업 목록
                    format = 'JPEG',    # 저장 포맷
                    options = {'quality':90},   # 옵션 퀄리티 90 은 무슨 뜻??
                )
    
        
class Comment(models.Model):    # models.Model 을 상속받음.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    # foreignKey table에 대한 정보를 변수로 입력. user가 1로 작용. 1:N 관계에서.
    # on_delete=models.CASCADE 는 특정한 유저가 사라지면 게시글도 사라지도록 하는 코드.
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # 2중 1:N 관계에 걸린다. user와 N, Post와 N.
    content = models.TextField()
    

django/insta/posts/forms.py
from django import forms
from .models import Post, Comment, Image


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content',]
        

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file',]
        

ImageFormSet = forms.inlineformset_factory(Post, Image, form=ImageForm, extra=3)
        
        
class CommentForm(forms.ModelForm):
    content = forms.CharField(label = '', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'댓글을 작성하세요.'})) # 한 줄짜리 input tag로 변경.
    
    class Meta:
        model = Comment
        fields = ['content',]

django/insta/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import PostForm, CommentForm, ImageFormSet
from .models import Post, Comment
from django.db import transaction
from itertools import chain
from django.http import JsonResponse


def explore(request):
    posts = Post.objects.order_by('-id').all()
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {
                                            'posts': posts, 
                                            'comment_form': comment_form,
                                        })


@login_required
def list(request):
    # posts = Post.objects.order_by('-id').all()
    # 1. 내가 follow하고 있는 사람들의 리스트
    followings = request.user.followings.all()
    # 2. followings 변수와 나를 묶음
    followings = chain(followings, [request.user])
    # 3. 이 사람들이 작성한 Post들만 뽑아옴.
    posts = Post.objects.filter(user__in=followings).order_by('-id')
    # 내림차순 정렬을 해서 가져옴.order_by('-id') 
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {'posts': posts, 'comment_form': comment_form})


# from django.contrib.auth.decorators import login_required     @ : 데코레이터, 파이썬에서 쓰이는 문법, 함수 바로 위쪽에 메소드로써 적용. 아래부분을 데코레이터의 파라미터로 적용.
@login_required         # login 이 충족이 되었는지 검사하고 충족하지 않았으면 login 함수 실행. 그리고 주소에 /?next=/posts/create가 남음.
def create(request):
    if request.method == 'POST':
        # request.POST #=> {'content':'asdf', 'user':'1'}
        post_form = PostForm(request.POST)   # 원래 data=request.POST, files=request.FILES 를 줄인 거임.
        image_formset = ImageFormSet(request.POST, request.FILES)
        if post_form.is_valid() and image_formset.is_valid():        # 데이터베이스에 넣어도 문제 없느냐? 묻는 코드.
            post= post_form.save(commit=False)
            post.user = request.user
            
            # from django.db import transaction
            with transaction.atomic():
                # 첫번째 포스트가 먼저 생성이 되야하고
                post.save()          # 실제 데이터 베이스에 저장. 그래야 id값이 나오니깐요.
                # 두번째 생성된 포스트를 바탕으로
                image_formset.instance = post   # 난 얘꺼다. 표시하기~~!
                image_formset.save() # 실제 데이터베이스에 저장
                # 사고를 방지하는 메소드가 있다. 순서에 관한 사고.
            
            
            return redirect('posts:list')
    else:
        post_form = PostForm()
        # 이미지 폼셋도 넘겨주자
        image_formset = ImageFormSet()
    return render(request, 'posts/form.html', {
                                            'post_form' : post_form, 
                                            'image_formset':image_formset,
        
    }) # 틀을 잡고 살을 붙여나가는 방식으로 진행할 예정. 딕셔너리는 몇줄로 이루어져도 괜찮음.


@login_required
def update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if post.user != request.user:       # id가 다른 경우 거르는 if문을 제일 위에 작성하는 것.
        return redirect('posts:list')
        
    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)
        image_formset = ImageFormSet(request.POST, request.FILES, instance=post)
        if post_form.is_valid() and image_formset.is_valid():
            post_form.save()
            image_formset.save()
            return redirect('posts:list')
    else:
        post_form = PostForm(instance=post)
        image_formset = ImageFormSet(instance=post)
    return render(request, 'posts/form.html', {'post_form' : post_form, 'image_formset':image_formset,})
    

@login_required    
def delete(request, post_id):
    # post = Post.objects.get(id=post_id)
    post = get_object_or_404(Post, id=post_id)
    
    if post.user != request.user:       # id가 다른 경우 거르는 if문을 제일 위에 작성하는 것.
        return redirect('posts:list')
        
    post.delete()
    
    # if post.user != request.user:   
    #     post.delete()
    
    return redirect('posts:list')
    

# from django.views.decorators.http import require_POST
@login_required # 데코레이터도 순서에 영향을 받는다.
@require_POST   # POST로 오는 요청만 받겠다. 주소를 직접 입력하는 것은 GET요청방식이다.
def comment_create(request, post_id): 
    # post_id를 통해 post에 대한 정보를 받아와서 조작한다.
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False) # DB에 반영없이 객체만 만든다.
        comment.user = request.user
        comment.post_id = post_id
        comment.save()
        
    # return redirect('posts:list')
    return JsonResponse({
                            'id': comment.id, 
                            'postId': post_id, 
                            'username': comment.user.username,
                            'content': comment.content,
                        })
    

@require_http_methods(['GET', 'POST']) # require_POST,GET 과 같은 기능. 다양한 방식이 허용된다.
def comment_delete(request, post_id, comment_id):
    # from .models import Comment
    comment = get_object_or_404(Comment, id=comment_id)
    
    if comment.user != request.user:    # 다른사람이면 지우면 안된다.
        return redirect('posts:list')
        
    comment.delete()
    return redirect('posts:list')
    

@login_required
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if request.user in post.like_users.all():
        # 2. 좋아요 취소
        post.like_users.remove(request.user)
        liked = False
    else:
        # 1. 좋아요 !
        post.like_users.add(request.user) # requst.user 로그인된 유저.
        liked = True
        
    # return redirect('posts:list')
    # from django.http import JsonResponse
    return JsonResponse({'liked': liked, 'count': post.like_users.count()})
    

    

django/insta/posts/templates/posts/_post.html
<div class="card" style="width: 18rem;">
  <div class = "card-header">
    {% if post.user.profile.image %}
    <img src="{{ post.user.profile.image.url }}" width="25" alt="">
    {% endif %}
    <a href="{% url 'people' post.user.username %}">{{ post.user.username }}</a>
  </div>
  <div id="post_{{ post.id }}" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      {% for image in post.image_set.all %}
      <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
        <img src="{{ image.file.url }}" class="card-img-top" alt="{{ image.file }}">
      </div>
      {% endfor %}
    </div>
  <a class="carousel-control-prev" href="#post_{{ post.id }}" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#post_{{ post.id }}" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  
  <div class="card-body">
  
      
    <i class="{% if user in post.like_users.all %}fas{% else %}far{% endif %} fa-heart like-button" data-id="{{ post.id }}"></i>
      
      
     
    
    <p class ="card-text">
      <span id="like-count-{{ post.id }}">{{ post.like_users.count }}</span>명이 좋아합니다.
    </p>
  </div>
  <div class="card-body">
    <p class="card-text">{{ post.content }}</p>
    {% if post.user == user %}
    <a href="{% url 'posts:update' post.id%}" class="btn btn-info">Edit</a>
    <a href="{% url 'posts:delete' post.id%}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>
  <div class="card-body" id="comment-list-{{ post.id }}">
    {% for comment in post.comment_set.all %}
      <div class = "card-text">
        <strong>{{ comment.user.username }} </strong>{{ comment.content }}
        {% if comment.user == user %}
        <!--댓글 작성과 같은 유저가 아니면 안보여주기 -->
        <a href="{% url 'posts:comment_delete' post.id comment.id %}">삭제</a>
        {% endif %}
      </div>
    {% empty %}
    <!--  <div class = "card=text"> 댓글이없습니다.</div>-->
    {% endfor %}
  </div>
  {% if user.is_authenticated %}
  <form action="{% url 'posts:comment_create' post.id %}" method = "POST" class="comment-form">
    {% csrf_token %}
    <!-- getbootstrap -> button addons -->
    <div class="input-group">
      {{ comment_form }}
      <div class="input-group-append">
        <input type="submit" value="Submit" class="btn btn-primary"/>
      </div>
    </div>
  </form>
  {% endif %}
</div>

django/insta/posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block container %}

<h1> New Post </h1>

<form method="post", enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
   
</form>

{% endblock %}

django/insta/posts/templates/posts/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block container %}

<h1> Post Form </h1>

<form method="post", enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {{ image_formset.as_p }}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
   
</form>

{% endblock %}

django/insta/posts/templates/posts/list.html
{% extends 'base.html' %}

{% block container %}

<h1> Post List </h1>

{% for post in posts %}

{% include 'posts/_post.html' %}

{% endfor %}

<script>
    const likeButtons = document.querySelectorAll('.like-button');
    likeButtons.forEach(function(button){
        button.addEventListener('click', function(event){
            console.log(event);
            const postId = event.target.dataset.id;
            axios.get(`/posts/${postId}/like`)
                    .then(function(response){
                        // response.data // {liked: true, count: 1}
                        document.querySelector(`#like-count-${postId}`).innerText = response.data.count
                        if (response.data.liked) {
                            event.target.classList.remove('far')
                            event.target.classList.add('fas')
                        } else {
                            event.target.classList.remove('fas')
                            event.target.classList.add('far')
                        }
                    });
        });
    });
    
    
    const commentForms = document.querySelectorAll('.comment-form')
    commentForms.forEach(function(form){
        
        form.addEventListener('submit', function(event){
            event.preventDefault()  // post요청 자체를 막아버리겠다. 
            console.log(event)
            // event.target === form
            const data = new FormData(event.target)
            // Inspect FormData
            // for (const item of data.entries()){
            //     console.log(item)
            // }
            axios.post(event.target.action, data) // form태그가 들고있는 action이란 속성의 값을 가져옴.
                .then(function(response){
                    const comment = response.data
                    const commentList = document.querySelector(`#comment-list-${comment.postId}`) // 동적으로 변하는 값이니까 빽틱`을 쓴다.
                    const newComment = `<div class = "card-text">
                        <strong>${comment.username} </strong>${comment.content}
                        <a href="/posts/${comment.postId}/comments/${comment.id}/delete/">삭제</a>
                    </div>`
                    commentList.insertAdjacentHTML('beforeend', newComment)
                    event.target.reset()    // 댓글작성란 비우기!
                })
        })
    })
    
</script>

{% endblock %}