django/cbv/accounts/urls.py
from django.urls import path
from . import views
# app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name = 'login')
]

django/cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('person/', include('person.urls')),
]

django/cbv/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [
    # path('', views.list, name = 'list'),
    path('', views.PersonList.as_view(), name = 'list'),
    # path('create/', views.create, name = 'create'),
    path('create/', views.PersonCreate.as_view(), name = 'create'),
    
]

django/cbv/accounts/models.py
from django.db import models

# Create your models here.

django/cbv/person/models.py
from django.db import models
from django.core.validators import EmailValidator, MinValueValidator

# Create your models here.
class Person(models.Model):
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100, validators = [EmailValidator(message= '이메일 형식에 맞지 않습니다.')])
    age = models.IntegerField(validators = [MinValueValidator(20, message = '미성년자 논노!')])

django/cbv/person/forms.py
from django import forms
from .models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'
        

django/cbv/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView


# Create your views here.
class Login(LoginView):
    pass

django/cbv/person/views.py
from django.shortcuts import render, redirect
from .models import Person
from .forms import PersonForm
from django.views.generic import ListView, CreateView   # 상속받기.
from django.contrib.auth.mixins import LoginRequiredMixin


class PersonList(ListView):
    model = Person  # 모델에서 꺼내오는 데이터 Person
    context_object_name = 'person'  # html에 쓰일 변수 'person'
    # urls.py 도 수정해야함.


# def list(request):
#     person = Person.objects.all()
#     return render(request, 'person/person_list.html', {'person': person})


# def create(request):
#     if request.method == 'POST':
#         form = PersonForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('person:list')
#     else:
#         form = PersonForm()
        
#     return render(request, 'person/person_form.html', {'form':form})

class PersonCreate(LoginRequiredMixin, CreateView):
    model = Person
    form_class = PersonForm
    success_url = '/person/'

django/cbv/person/templates/person/person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Person Form</h1>
    <form method = "POST">
    	{% csrf_token %}
    	{{ form }}
        <input type = "submit" value = "Submit"/>
    </form>
</body>
</html>

django/cbv/person/templates/person/person_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> Person List </h1>
    <a href = "{% url 'person:create' %}">New Person</a>
    <ul>
    
        {% for p in person %}
        <li>
        	{{ p.last_name}} - {{ p.email }} - {{p.age }}
        </li>
        {% endfor %}
    
    </ul>
</body>
</html>